lab4_1: lab4_1.o lab4_2
	gcc lab4_1.o -o lab4_1

lab4_1.o: lab4_1.c
	gcc -c lab4_1.c 

lab4_2: lab4_2.o
	gcc lab4_2.o -o lab4_2

lab4_2.o: lab4_2.c
	gcc -c lab4_2.c

clean:
	rm lab4_1 lab4_1.o lab4_2 lab4_2.o
